In [1]:
import pyuff
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
%load_ext autoreload
%autoreload 2
%matplotlib qt

from lib import Experiment, mac, complex_mac, slide_grid_and_calculate_mac

In [2]:
exp1 = Experiment('Scan24(defected_side_9mm)_v2.uff', 'Modeset_24.unv')

Reading experimental and mode set files...
Files have been read.
Extracting experimental data...


100%|█████████████████████████████████████████████████████████████████████████████| 918/918 [00:00<00:00, 59661.45it/s]

Extracting mode shapes data...


Detected geometry: 75x97 points
Constructing mode shapes...
Experimental data processed successfully.


In [ ]:
sets = exp1.raw_data_file.read_sets()

In [ ]:
sets[7279:]

In [179]:
wds = exp1.fit_curves((0,37))

  6%|████▌                                                                      | 1543/25600 [01:15<1:22:19,  4.87it/s]c:\programdata\anaconda3\envs\ndt\lib\site-packages\scipy\optimize\minpack.py:828: OptimizeWarning: Covariance of the parameters could not be estimated
  warnings.warn('Covariance of the parameters could not be estimated',
100%|██████████████████████████████████████████████████████████████████████████| 25600/25600 [2:17:40<00:00,  3.10it/s]


In [180]:
wbp = exp1.calculate_wbp()

In [182]:
for x,each in enumerate(wbp):
    if each <0:
        wbp[x] = np.average(wbp)

In [183]:
s = plt.imshow(np.rot90(wbp.reshape(exp1.y_length, exp1.x_length)[:87,:]))
plt.colorbar(s)

In [157]:
from scipy import ndimage
import matplotlib.pyplot as plt
fig = plt.figure()
plt.set_cmap('jet')  # show the filtered result in grayscale
ax1 = fig.add_subplot(121)  # left side
ax2 = fig.add_subplot(122)  # right side
ascent = np.rot90(wbp.reshape(exp1.y_length, exp1.x_length)[:,:])
result = ndimage.median_filter(ascent, size=(2,2))
ax1.imshow(ascent)
ax2.imshow(result)
plt.show()

In [137]:
np.max(np.rot90(wbp.reshape(exp1.y_length, exp1.x_length)[:,:]))

28324567.980941985

In [142]:
import matplotlib.colors as colors
fig, ax = plt.subplots()
pcm = ax.pcolor(np.rot90(wbp.reshape(exp1.y_length, exp1.x_length)[:87,:]), norm=colors.LogNorm(), cmap='jet')
fig.colorbar(pcm)

In [159]:
np.max(exp1.WDs)

1.3843710130134103e-09

In [85]:
pcm = plt.pcolormesh(exp1.xs.reshape(exp1.y_length, exp1.x_length), exp1.ys.reshape(exp1.y_length, exp1.x_length), wbp.reshape(exp1.y_length, exp1.x_length), vmin=0., vmax=1., cmap='RdBu_r')
plt.show()

<ipython-input-85-58acb39da62d>:1: MatplotlibDeprecationWarning: shading='flat' when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading='auto', 'nearest' or 'gouraud', or set rcParams['pcolor.shading'].  This will become an error two minor releases later.
  pcm = plt.pcolormesh(exp1.xs.reshape(exp1.y_length, exp1.x_length), exp1.ys.reshape(exp1.y_length, exp1.x_length), wbp.reshape(exp1.y_length, exp1.x_length), vmin=0., vmax=1., cmap='RdBu_r')


AttributeError: 'QuadMesh' object has no attribute 'plot'

In [169]:
exp1.plot_fit_curve(10000)

In [178]:
i=0
for number, each in enumerate(exp1.coeffs[:,2]):
    if each < 0:
        i+=1
        print(number, each)
print(i)

2 -2.9715114016984705e-12
3 -4.4367292646262635e-12
4 -6.65292395430048e-11
5 -1.6972113027885195e-12
6 -9.513162418432986e-11
7 -2.0365515874520566e-12
8 -1.2745645673991616e-13
9 -9.075287542884633e-14
10 -4.744751591373366e-14
11 -1.511692096737816e-13
12 -4.255884437375168e-14
13 -4.496237444091867e-15
14 -8.784146470119671e-14
15 -4.605424745609421e-13
16 -7.472686888278144e-12
17 -3.556520239771198e-11
18 -5.43526869561333e-12
19 -1.0668402450204934e-13
20 -6.20370906777456e-14
21 -1.2692368459292815e-13
22 -1.5598432266547645e-13
23 -8.934055646637938e-14
27 -1.8900647790245598e-13
47 -3.549376455783719e-12
48 -3.968981573577423e-12
49 -8.095382897518678e-12
50 -2.5762570893124805e-11
51 -1.3662496225581589e-11
52 -1.5461609064601697e-11
53 -1.9758750653632443e-11
54 -2.3663742793666945e-11
55 -2.1978814681771087e-11
56 -3.5364474213181394e-11
57 -2.6820387236840784e-11
58 -3.729541221552728e-11
59 -4.9245889430571435e-11
60 -6.159013736515252e-11
61 -8.612735102256477e-11
62 -7

3501 -1.2595263209993645e-08
3502 -1.892390757414396e-08
3503 -2.5878913338310897e-08
3504 -3.4502122418842605e-08
3505 -3.934420494153605e-08
3506 -3.7507939040873745e-08
3507 -4.227969860992696e-08
3508 -5.2198840457653256e-08
3509 -5.268101344831801e-08
3510 -5.493643913129439e-08
3511 -5.1927835704177026e-08
3512 -5.395909074939672e-08
3513 -4.698286461338721e-08
3514 -4.363854655104855e-08
3515 -4.260387368653221e-08
3516 -3.812758122532492e-08
3517 -3.25868567892644e-08
3518 -2.291900021212446e-08
3519 -1.9073789135989182e-08
3520 -1.5901317574036303e-08
3521 -8.953083676231846e-09
3522 -7.815637746645597e-09
3523 -6.779227439809454e-09
3524 -3.877429747010972e-09
3525 -2.7025832752242323e-09
3526 -2.257507921329703e-09
3527 -1.906935983675118e-09
3528 -1.4979978976779038e-09
3529 -1.2343894309972988e-09
3530 -1.1117770149598605e-09
3531 -9.265564103655201e-10
3532 -7.515990374427781e-10
3533 -6.617757486493254e-10
3534 -5.731989504830665e-10
3535 -4.886211484100936e-10
3536 -4.5

13356 -8.085284939679547e-11
13357 -8.13413993698322e-11
13358 -8.701370453521823e-11
13359 -8.735557174160114e-11
13360 -8.594551786687852e-11
13361 -8.654717042900424e-11
13362 -8.838137406224351e-11
13363 -9.117185326075597e-11
13364 -8.957975349669684e-11
13365 -9.049958810980665e-11
13366 -9.22043874686174e-11
13367 -9.79236745451302e-11
13368 -9.452572242952082e-11
13369 -1.01353286207052e-10
13370 -9.433823345955005e-11
13371 -1.0082536165889138e-10
13372 -1.0086469888993157e-10
13373 -1.0370994002197127e-10
13374 -1.0665391788309146e-10
13375 -1.0689604663886496e-10
13376 -1.0783495591541659e-10
13377 -1.1338136055545363e-10
13378 -1.1610619538347077e-10
13379 -1.082112744078963e-10
13380 -1.1420417497267027e-10
13381 -1.1495150917878923e-10
13382 -1.1589832450550385e-10
13383 -1.170788198912514e-10
13384 -1.1638492173009946e-10
13385 -1.2131963450133104e-10
13386 -1.253416982605779e-10
13387 -1.2065587096675285e-10
13388 -1.2537251915509566e-10
13389 -1.2688219719728612e-10
13

14325 -1.521546605554762e-11
14326 -1.490801619479375e-11
14327 -1.5591432585738593e-11
14328 -1.4714541037329644e-11
14329 -1.5196003377572917e-11
14330 -1.572093102000672e-11
14331 -1.4987411345314863e-11
14332 -1.561227290968181e-11
14333 -1.5387464647684298e-11
14334 -1.5340012773021197e-11
14335 -1.5379268866504398e-11
14336 -1.5834041554726494e-11
14337 -1.592899265004225e-11
14338 -1.5793694526567194e-11
14339 -1.549359883036005e-11
14340 -1.64903105912381e-11
14341 -1.5304952046005124e-11
14342 -1.5708281439741236e-11
14343 -1.5682281730735657e-11
14344 -1.6044787732656433e-11
14345 -1.543468626211981e-11
14346 -1.5920820971163673e-11
14347 -1.615647290142235e-11
14348 -1.6163047529961455e-11
14349 -1.5754239184036728e-11
14350 -1.5758823217978265e-11
14351 -1.6274561425468586e-11
14352 -1.569253952305233e-11
14353 -1.6162633524008698e-11
14354 -1.594176946070482e-11
14355 -1.5899114905985234e-11
14356 -1.6324034996546516e-11
14357 -1.6120124576695568e-11
14358 -1.6425047248398

16842 -1.2346990492450873e-11
16843 -1.1820075469798845e-11
16844 -1.0741778833286907e-11
16845 -8.592952737603696e-12
16846 -1.021550883175526e-11
16847 -1.0643634008338329e-11
16848 -1.0541545129301229e-11
16849 -1.114531340646727e-11
16850 -1.0738212482200226e-11
16851 -1.0315762358987393e-11
16852 -1.1273581650183705e-11
16853 -9.704433407185689e-12
16854 -1.0011656581661812e-11
16855 -1.1154537055927833e-11
16856 -1.0552835029353028e-11
16857 -9.51575982677565e-12
16858 -9.812585218457387e-12
16859 -1.297402977009241e-11
16860 -1.2618843434992034e-11
16861 -1.0628406710273269e-11
16862 -8.59848444605558e-12
16863 -8.588450006700542e-12
16864 -1.007411253312231e-11
16865 -1.037850753493838e-11
16866 -9.114456541211426e-12
16867 -1.0391113288838041e-11
16868 -1.034348760261888e-11
16869 -8.37868377868859e-12
16870 -9.266748125417361e-12
16871 -9.55228771559612e-12
16872 -8.70439695110722e-12
16873 -8.648693039644093e-12
16874 -1.0144123741781381e-11
16875 -8.608062208826428e-12
1687

17789 -7.1417203682609775e-12
17790 -7.384573203512241e-12
17791 -8.302012974254288e-12
17792 -8.318115819196424e-12
17793 -8.11106245726456e-12
17794 -7.492633021367493e-12
17795 -7.327549372571411e-12
17796 -8.39723370151238e-12
17797 -9.013989801033207e-12
17798 -7.738961213264494e-12
17799 -8.135120227160554e-12
17800 -8.003167178190161e-12
17801 -7.552622714699546e-12
17802 -7.936440964416704e-12
17803 -7.91831958473942e-12
17804 -7.601668881344137e-12
17805 -7.498287806634528e-12
17806 -7.412125444519459e-12
17807 -8.21039141760817e-12
17808 -7.66659691730357e-12
17809 -8.720869413991112e-12
17810 -7.0818217884896e-12
17811 -7.825561202910445e-12
17812 -8.165435046296275e-12
17813 -7.189093694724709e-12
17814 -7.591643568444398e-12
17815 -8.25095190345176e-12
17816 -7.331514605152667e-12
17817 -7.591344715450198e-12
17818 -6.5712670903348114e-12
17819 -7.694116291613795e-12
17820 -8.315952508777449e-12
17821 -7.656740997013348e-12
17822 -8.024943414166982e-12
17823 -8.16206962939

20051 -9.735790968464279e-13
20052 -9.92547640203272e-13
20053 -1.0266233540044646e-12
20054 -9.505668846708013e-13
20055 -1.0998857387256103e-12
20056 -1.061226898655211e-12
20057 -1.0678874686747285e-12
20058 -8.690523290113428e-13
20059 -1.083510475678969e-12
20060 -1.0066425492508784e-12
20061 -8.431324055322632e-13
20062 -1.1195299455073862e-12
20063 -1.2237974771166632e-12
20064 -1.001132111473381e-12
20065 -9.998656424947829e-13
20066 -1.119492099339579e-12
20067 -1.4714933699745199e-12
20068 -1.07648382997856e-12
20069 -1.2692227076399555e-12
20070 -9.27700045772706e-13
20071 -6.980908793823244e-13
20072 -1.0709670464400614e-12
20073 -1.093577409023052e-12
20074 -1.0361307470055928e-12
20075 -1.070533108530504e-12
20076 -9.511743220937291e-13
20077 -1.1277126637042853e-12
20078 -1.1711988513639942e-12
20079 -1.1942632953500174e-12
20080 -1.2218819293022544e-12
20081 -1.0877969427212663e-12
20082 -1.3019706603945743e-12
20083 -1.3893469038553297e-12
20084 -1.3375456363820206e-12

In [66]:
np.abs(exp1.velocities.T[25599])**2

array([2.17056024e-11, 3.24114132e-11, 2.47660390e-11, ...,
       9.80860783e-12, 5.11340121e-12, 4.23245088e-12])

In [26]:
plt.plot()

In [40]:
rs = np.empty(0)
for point_number in range(len(exp1.velocities)):
    x = int(point_number/75)
    y = 75 - (point_number - int(x*75))
    r = np.sqrt((x-0)**2 + (y-37)**2)
    rs = np.append(rs, r)
rs = rs.reshape(97,75)
plt.imshow(rs)

In [13]:
exp1.raw_data.T

array([[-1.76973e-07+3.63281e-06j,  5.23564e-06-3.20777e-06j,
        -3.47646e-06-2.21817e-07j, ...,  8.01032e-06-1.14535e-06j,
         1.58073e-06+7.99784e-07j, -1.58497e-06+3.11028e-06j],
       [ 5.55652e-06-1.23983e-06j,  3.13724e-06-2.66004e-06j,
         7.05386e-07-3.00706e-07j, ...,  4.74406e-06-9.86761e-07j,
        -1.66097e-07-2.65614e-06j, -3.33213e-06-1.78241e-06j],
       [ 4.20479e-06+8.00311e-07j,  6.08193e-06-3.24276e-06j,
        -9.12997e-06-7.94031e-06j, ...,  7.45045e-06-1.73460e-06j,
         1.75196e-07-3.39706e-06j, -1.15511e-05+2.06970e-06j],
       ...,
       [ 2.42124e-06-5.61449e-05j,  5.67316e-06-7.35215e-05j,
         4.42596e-05-2.98402e-05j, ...,  2.07346e-05-2.21423e-05j,
         2.45343e-05+1.07058e-05j,  3.08939e-05+5.15024e-06j],
       [-2.42390e-05-6.80656e-05j, -5.03399e-06-1.03193e-04j,
         6.64467e-06-2.99357e-05j, ...,  1.11530e-05-2.04037e-05j,
         3.07563e-05+1.04683e-09j,  2.80354e-05+6.43916e-06j],
       [ 4.41154e-06-6.10730

In [ ]:
len(radiuses)

In [ ]:
plt.plot(radiuses)

In [ ]:
75/2

In [5]:
velocities = exp1.velocities

In [14]:
exp1.velocities = np.abs(exp1.velocities)

In [7]:
velocities

array([[-1.51955e-08+3.11926e-07j,  4.78793e-07-1.06834e-07j,
         5.90706e-07+1.12431e-07j, ...,  2.11986e-07-4.91565e-06j,
        -1.99224e-06-5.59439e-06j,  3.35658e-07-4.64682e-06j],
       [ 4.99209e-07-3.05856e-07j,  4.15870e-07-3.52612e-07j,
         6.10491e-07-3.25502e-07j, ...,  5.28370e-07-6.84742e-06j,
        -3.55764e-07-7.29288e-06j,  3.76034e-07-5.68067e-06j],
       [-3.07607e-07-1.96270e-08j,  3.75267e-07-1.59976e-07j,
        -5.92089e-07-5.14939e-07j, ...,  3.07822e-06-2.07537e-06j,
         7.12635e-07-3.21057e-06j,  4.78562e-06-1.36524e-06j],
       ...,
       [ 5.51382e-07-7.88394e-08j,  4.73770e-07-9.85439e-08j,
         7.61078e-07-1.77193e-07j, ...,  2.02616e-06-2.16372e-06j,
         9.52684e-07-1.74288e-06j,  2.88959e-06+1.20784e-06j],
       [ 2.96046e-07+1.49787e-07j, -2.81839e-08-4.50703e-07j,
         2.13415e-08-4.13811e-07j, ...,  2.61976e-06+1.14315e-06j,
         2.55223e-06+8.68685e-11j,  2.16981e-06-6.36652e-07j],
       [-1.70956e-07+3.35478

In [ ]:
x = sets[2]['x']
y = sets[2]['y']

In [ ]:
for each in y[:100]:
    print(each)

In [ ]:
plt.scatter(x, y)

In [ ]:
frfs = exp1.raw_data.to_numpy()

In [ ]:
for each in frfs[:5]:
    print(each)

In [ ]:
temp = np.empty((0, len(velocitites[0])))
for each in velocitites:
    temp = np.append(temp, [each], axis = 0)

In [ ]:
velocitites = np.stack(velocitites)

In [ ]:
for num, each in enumerate(sets[4:]):
    if each['id1'] != 'Response Linear Spectrum':
        print(each, num)
        break

In [ ]:
len(exp1.raw_data)

In [ ]:
exp2 = Experiment('Scan25(healthy_side_9mm).uff', 'Modeset_25.unv')

In [ ]:
exp3 = Experiment('Scan_06_1_def0_laser1_pzt_1_v2.uff', 'modeset_06_1_side1_1.unv')

In [ ]:
exp4 = Experiment('Scan_06_1_def0_laser1_pzt_1_v2_double.uff', 'modeset_06_1_side1_2.unv')

In [ ]:
ms1 = exp3.stack_modeshapes(dims=2)
ms2 = exp4.stack_modeshapes(dims=2)

In [ ]:
mac = complex_mac(ms1,ms2)

In [ ]:
for j in range(1,15,6):
    for i in range(1,15,6):
        mac_m = slide_grid_and_calculate_mac(ms1, ms2, direction=(i,j), title='Shifted for '+str(i)+','+str(j))

In [ ]:
mac_m = slide_grid_and_calculate_mac(ms1, ms2, direction=(5,5))

In [ ]:
plt.imshow(mac, cmap = 'jet')
plt.colorbar()
print(np.max(mac_m))

In [ ]:
plt.imshow(np.rot90(mac), cmap='jet')
plt.colorbar()

In [ ]:
exp2 = Experiment('Scan30_9mm_defected_side_small_region.uff', 'Modeset_30.unv')

In [ ]:
exp3 = Experiment('Scan26_3mm.uff', 'Modeset_26.unv', geometry=(141, 191))

In [ ]:
dbrs = exp1.move_and_calculate_dbr_window((5,8), 1)

In [ ]:
dbrs_49 = np.empty((0, len(exp1.mode_shapes)))
central = (43, 38)#(42, 36)
for y_step in range(2,18,2):
    for x_step in range(2,18,2):
        print(x_step, y_step)
        print((int(central[0]- x_step/2), int(central[1]-y_step/2)), (int(central[0]+x_step/2), int(central[1]-y_step/2)), (int(central[0]-x_step/2), int(central[1]+y_step/2)), (int(central[0]+x_step/2), int(central[1]+y_step/2)))
        dbrs_49 = np.append(dbrs_49, [exp1.calculate_dbrs([(int(central[0]- x_step/2), int(central[1]-y_step/2)), (int(central[0]+x_step/2), int(central[1]-y_step/2)), (int(central[0]-x_step/2), int(central[1]+y_step/2)), (int(central[0]+x_step/2), int(central[1]+y_step/2))])], axis=0)

In [ ]:
exp1.visualize_modeshape(52)

In [ ]:
plt.plot(dbrs[3135])
plt.title("Defect-to-background ratio for defected region (5x8 points region)")
plt.xlabel('Number of mode shape')
plt.ylabel('DBR value')

In [ ]:
plot(exp1.DBRs['(40, 32) (45, 32) (40, 40) (45, 40) '])

In [9]:
from scipy.optimize import curve_fit

def func(x, a, b, c):
    return a * np.exp(-b * x) + c

xdata = np.linspace(0, 4, 50)
y = func(xdata, 2.5, 1.3, 0.5)
np.random.seed(1729)
y_noise = 0.8 * np.random.normal(size=xdata.size)
ydata = y + y_noise
plt.scatter(xdata, ydata, label='data')

In [12]:
popt, pcov = curve_fit(func, xdata, ydata)
pcov

array([[ 0.26971452,  0.12281392, -0.01044751],
       [ 0.12281392,  0.3308177 ,  0.07891343],
       [-0.01044751,  0.07891343,  0.03993415]])

In [11]:
plt.plot(xdata, func(xdata, *popt), 'r-',
         label='fit: a=%5.3f, b=%5.3f, c=%5.3f' % tuple(popt))